<?php

namespace Container6q9Hc7W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J46UgjHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J46UgjH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J46UgjH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.J46UgjH.App\\Entity\\MicroPost', NULL, 'Cannot autowire service ".service_locator.J46UgjH": it references class "App\\Entity\\MicroPost" but no such service exists.'],
        ], [
            'post' => 'App\\Entity\\MicroPost',
        ]);
    }
}
