<?php

namespace Container6q9Hc7W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CreateUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-user', [], 'create a new user account', false, #[\Closure(name: 'App\\Command\\CreateUserCommand')] function () use ($container): \App\Command\CreateUserCommand {
            return ($container->privates['App\\Command\\CreateUserCommand'] ?? $container->load('getCreateUserCommandService'));
        });
    }
}
