<?php

namespace ContainerXrAl3xZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.J46UgjH.App\Entity\MicroPost' shared service.
     *
     * @return \App\Entity\MicroPost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.J46UgjH": it references class "App\\Entity\\MicroPost" but no such service exists.');
    }
}
