<?php

namespace ContainerXrAl3xZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MicroPostType' shared autowired service.
     *
     * @return \App\Form\MicroPostType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MicroPostType'] = new \App\Form\MicroPostType();
    }
}
