<?php

namespace ContainerXrAl3xZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostManageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PostManageController' shared autowired service.
     *
     * @return \App\Controller\PostManageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PostManageController'] = $instance = new \App\Controller\PostManageController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\PostManageController', $container));

        return $instance;
    }
}
