<?php

namespace Container0uBBMFF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WRvHM14Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WRvHM14' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WRvHM14'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'userToUnfollow' => ['privates', '.errored..service_locator.WRvHM14.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.WRvHM14": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'userToUnfollow' => 'App\\Entity\\User',
        ]);
    }
}
