<?php

namespace ContainerNYuJUVC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VVCoPw4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VVCoPw4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VVCoPw4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'posts' => ['privates', 'App\\Repository\\MicroPostRepository', 'getMicroPostRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.VVCoPw4.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.VVCoPw4": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'posts' => 'App\\Repository\\MicroPostRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
