<?php

namespace ContainerJzNFHBt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPost3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fh2tw1g.App\Entity\MicroPost' shared service.
     *
     * @return \App\Entity\MicroPost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fh2tw1g": it references class "App\\Entity\\MicroPost" but no such service exists.');
    }
}
