<?php

namespace ContainerRCZrsfD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTitleSearchTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TitleSearchType' shared autowired service.
     *
     * @return \App\Form\TitleSearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TitleSearchType'] = new \App\Form\TitleSearchType();
    }
}
