<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIKt5sIx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIKt5sIx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIKt5sIx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIKt5sIx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIKt5sIx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IKt5sIx',
    'container.build_id' => '13bd95ed',
    'container.build_time' => 1680550917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIKt5sIx');
