<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqaZtwx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqaZtwx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqaZtwx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqaZtwx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSqaZtwx\App_KernelDevDebugContainer([
    'container.build_hash' => 'SqaZtwx',
    'container.build_id' => '9c73694b',
    'container.build_time' => 1680688524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqaZtwx');
