<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6q9Hc7W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6q9Hc7W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6q9Hc7W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6q9Hc7W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6q9Hc7W\App_KernelDevDebugContainer([
    'container.build_hash' => '6q9Hc7W',
    'container.build_id' => '51b81ee6',
    'container.build_time' => 1680680537,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6q9Hc7W');
